// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using User_Database;

namespace User_Database
{
    public partial class UserDBContext
    {
        private IUserDBContextProcedures _procedures;

        public virtual IUserDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new UserDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IUserDBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class UserDBContextProcedures : IUserDBContextProcedures
    {
        private readonly UserDBContext _context;

        public UserDBContextProcedures(UserDBContext context)
        {
            _context = context;
        }
    }
}
