// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace User_Database;

public partial class Organizations
{
    public int Orgid { get; set; }

    public string? OrgName { get; set; }

    public bool? IsActive { get; set; }
}