// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using User_Database;

#nullable disable

namespace User_Database.Configurations
{
    public partial class OrganizationsConfiguration : IEntityTypeConfiguration<Organizations>
    {
        public void Configure(EntityTypeBuilder<Organizations> entity)
        {
            entity.HasKey(e => e.Orgid);

            entity.Property(e => e.OrgName).HasMaxLength(200);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Organizations> entity);
    }
}
